"""消金领域本体片段 — 对齐 docs/ONTOLOGY_AIBI_DATA_AGENT.md 第 4 章。"""
from __future__ import annotations

from typing import Any

CONSUMER_FINANCE_FRAGMENT: dict[str, Any] = {
    "domain": "consumer_finance",
    "description": "消费金融轻量本体主干：客户是谁 → 申请了什么 → 合约/账户状态 → 为何逾期/风险",
    "object_types": [
        {
            "key": "Party",
            "display_name": "主体",
            "definition": "参与信贷业务的自然人或机构等主体抽象",
            "parent_key": None,
            "aliases": ["参与方", "交易对手"],
            "cluster": "主体",
        },
        {
            "key": "Person",
            "display_name": "个人",
            "definition": "自然人客户",
            "parent_key": "Party",
            "aliases": ["个人客户", "借款人"],
            "cluster": "主体",
            "typical_properties": ["标识", "职业", "收入区间"],
        },
        {
            "key": "Organization",
            "display_name": "机构",
            "definition": "法人或组织客户",
            "parent_key": "Party",
            "aliases": ["企业", "对公客户"],
            "cluster": "主体",
            "typical_properties": ["标识", "行业", "规模"],
        },
        {
            "key": "LoanApplication",
            "display_name": "贷款申请",
            "definition": "客户发起的信贷申请",
            "parent_key": None,
            "aliases": ["进件", "申请单"],
            "cluster": "产品与合约",
        },
        {
            "key": "LoanContract",
            "display_name": "贷款合约",
            "definition": "获批后的贷款合同",
            "parent_key": None,
            "aliases": ["借款合同", "授信合约"],
            "cluster": "产品与合约",
            "typical_properties": ["利率", "额度", "期限", "费项"],
        },
        {
            "key": "CreditProduct",
            "display_name": "信贷产品",
            "definition": "可售卖的信贷产品定义",
            "parent_key": None,
            "aliases": ["贷款产品", "产品"],
            "cluster": "产品与合约",
            "typical_properties": ["利率", "额度", "期限", "费项"],
        },
        {
            "key": "LoanAccount",
            "display_name": "贷款账户",
            "definition": "合约开立后的放款/还款账户",
            "parent_key": None,
            "aliases": ["借据账户", "贷款户"],
            "cluster": "账户与行为",
            "typical_properties": ["余额", "逾期天数", "动支"],
        },
        {
            "key": "Transaction",
            "display_name": "交易",
            "definition": "账户上的资金往来流水",
            "parent_key": None,
            "aliases": ["流水", "账务交易"],
            "cluster": "账户与行为",
        },
        {
            "key": "RepaymentBehavior",
            "display_name": "还款行为",
            "definition": "账户还款表现与行为特征",
            "parent_key": None,
            "aliases": ["还款表现", "还款"],
            "cluster": "账户与行为",
            "typical_properties": ["余额", "逾期天数"],
        },
        {
            "key": "RiskEvent",
            "display_name": "风险事件",
            "definition": "逾期、催收、欺诈等风险触发事件",
            "parent_key": None,
            "aliases": ["风险", "逾期事件"],
            "cluster": "风险",
            "typical_properties": ["等级", "时间", "处置状态"],
        },
        {
            "key": "Collateral",
            "display_name": "抵押物",
            "definition": "担保合约的抵押/质押物",
            "parent_key": None,
            "aliases": ["担保物", "押品"],
            "cluster": "产品与合约",
        },
        {
            "key": "AcquisitionChannel",
            "display_name": "获客渠道",
            "definition": "申请来源渠道",
            "parent_key": None,
            "aliases": ["渠道", "Channel"],
            "cluster": "获客与运营",
            "typical_properties": ["渠道成本", "转化"],
        },
        {
            "key": "ScorecardModel",
            "display_name": "评分卡模型",
            "definition": "用于申请评分的决策模型",
            "parent_key": None,
            "aliases": ["评分卡", "Scorecard"],
            "cluster": "决策资产",
            "typical_properties": ["分数", "口径", "版本"],
        },
        {
            "key": "RiskFeature",
            "display_name": "风险特征",
            "definition": "喂入评分/策略的风险特征",
            "parent_key": None,
            "aliases": ["特征", "Feature"],
            "cluster": "决策资产",
            "typical_properties": ["分数", "口径", "版本"],
        },
    ],
    "link_types": [
        {
            "key": "applies_for",
            "display_name": "申请",
            "from_key": "Party",
            "to_key": "LoanApplication",
            "cardinality": "1-n",
            "definition": "主体发起贷款申请",
        },
        {
            "key": "results_in",
            "display_name": "生成合约",
            "from_key": "LoanApplication",
            "to_key": "LoanContract",
            "cardinality": "1-1",
            "definition": "申请获批后生成贷款合约",
        },
        {
            "key": "offered_as",
            "display_name": "产品提供",
            "from_key": "CreditProduct",
            "to_key": "LoanApplication",
            "cardinality": "1-n",
            "definition": "信贷产品作为申请标的",
        },
        {
            "key": "opens",
            "display_name": "开立账户",
            "from_key": "LoanContract",
            "to_key": "LoanAccount",
            "cardinality": "1-n",
            "definition": "合约开立贷款账户",
        },
        {
            "key": "has_transaction",
            "display_name": "拥有交易",
            "from_key": "LoanAccount",
            "to_key": "Transaction",
            "cardinality": "1-n",
            "definition": "账户产生交易流水",
        },
        {
            "key": "exhibits",
            "display_name": "表现还款行为",
            "from_key": "LoanAccount",
            "to_key": "RepaymentBehavior",
            "cardinality": "1-n",
            "definition": "账户表现出还款行为",
        },
        {
            "key": "triggers",
            "display_name": "触发风险",
            "from_key": "LoanAccount",
            "to_key": "RiskEvent",
            "cardinality": "1-n",
            "definition": "账户触发风险事件",
        },
        {
            "key": "secured_by",
            "display_name": "担保于",
            "from_key": "LoanContract",
            "to_key": "Collateral",
            "cardinality": "n-n",
            "definition": "合约由抵押物担保",
        },
        {
            "key": "sourced_from",
            "display_name": "来源于",
            "from_key": "LoanApplication",
            "to_key": "AcquisitionChannel",
            "cardinality": "n-1",
            "definition": "申请来自获客渠道",
        },
        {
            "key": "scores",
            "display_name": "评分",
            "from_key": "ScorecardModel",
            "to_key": "LoanApplication",
            "cardinality": "n-n",
            "definition": "评分卡对申请打分",
        },
        {
            "key": "feeds",
            "display_name": "喂入特征",
            "from_key": "RiskFeature",
            "to_key": "ScorecardModel",
            "cardinality": "n-n",
            "definition": "风险特征喂入评分卡",
        },
    ],
    "clusters": {
        "主体": {
            "classes": ["Person", "Organization", "Household"],
            "typical_properties": ["标识", "职业", "收入区间"],
            "typical_relations": ["belongs_to", "related_party"],
        },
        "产品与合约": {
            "classes": ["CreditProduct", "LoanContract", "Limit"],
            "typical_properties": ["利率", "额度", "期限", "费项"],
            "typical_relations": ["issues", "underwrites"],
        },
        "账户与行为": {
            "classes": ["LoanAccount", "Transaction", "Repayment"],
            "typical_properties": ["余额", "逾期天数", "动支"],
            "typical_relations": ["posts_to", "pays"],
        },
        "风险": {
            "classes": ["RiskEvent", "CollectionCase", "FraudSignal"],
            "typical_properties": ["等级", "时间", "处置状态"],
            "typical_relations": ["triggers", "investigated_as"],
        },
        "获客与运营": {
            "classes": ["Channel", "Campaign", "Case"],
            "typical_properties": ["渠道成本", "转化"],
            "typical_relations": ["sources"],
        },
        "决策资产": {
            "classes": ["Scorecard", "Feature", "StrategyRule"],
            "typical_properties": ["分数", "口径", "版本"],
            "typical_relations": ["derived_from"],
        },
    },
}


DOMAIN_FRAGMENTS: dict[str, dict[str, Any]] = {
    "consumer_finance": CONSUMER_FINANCE_FRAGMENT,
}


def get_domain_fragment(name: str | None) -> dict[str, Any] | None:
    if not name:
        return None
    return DOMAIN_FRAGMENTS.get(name)
